package com.ircnet.service.operserv.kline;

/**
 * K-Line types.
 */
public enum KLineType {
    /**
     * K-Line has been synced with the web service.
     */
    SYNCED,

    /**
     * K-Line has not been synced with the web service.
     */
    NOT_SYNCED,

    /**
     * K-Line has been generated by a list of Tor exit nodes.
     */
    TOR
}
